---
apiVersion: v1
baseDomain: test.example.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  replicas: 2
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: compact-cluster
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 192.168.124.0/24
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  baremetal:
    hosts:
      - name: master-0
        role: master
        bootMACAddress: 52:54:00:e7:05:72
      - name: master-1
        role: master
        bootMACAddress: 52:54:00:95:fd:f3
      - name: master-2
        role: master
        bootMACAddress: 52:54:00:e8:b9:18
      - name: worker-0
        role: worker
        bootMACAddress: 52:54:00:a8:39:26
      - name: worker-1
        role: worker
        bootMACAddress: 52:54:00:c8:f3:09
    apiVIP: "192.168.124.125"
    ingressVIP: "192.168.124.126"
imageContentSources: ### Replace with your own mirrored registry
- mirrors:
  - quay-mirror.example.com:8443/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - quay-mirror.example.com:8443/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
pullSecret: '{"auths":{"quay-mirror.example.com:8443":{"auth":"eW91cl9yZWdpc3RyeV91c2VybmFtZTp5b3VyX3JlZ2lzdHJ5X3Bhc3N3b3JkCg=="}}}' ### Replace with your credentials
sshKey: "<YOUR_SSH_PUB_KEY>"
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  Your Trust Bundle
  If It Is Needed
  -----END CERTIFICATE-----
